### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by maghuro** [maverickcdn/wicens#1]
Update checker menu option, and auto update, without loosing user settings, or prompt to backup and then, on first run, prompt to restore if backup found.

You can check for a new version or MD5 comparison for small changes.

**Comment by maverickcdn** [comment]
Added to ver2 release

**Comment by maghuro** [comment]
Does it send an email whenever an updated version is available?

**Comment by maverickcdn** [comment]
Not at the moment  just when the user is running the script.   Currently only checks with user execution not cron, but I'll look into it.  Thanks

**Comment by maghuro** [comment]
Nice work! My best regards

**Comment by maverickcdn** [comment]
v2.1 has optional email update notifications.  Checks every 4 hours with cron, only Emails 1 notification

**Comment by maghuro** [comment]
Regarding new v2.1, when I press "n" to enable update notifications, the script does nothing and exits.
Maybe because I've already a config file generated by v2.0?

https://user-images.githubusercontent.com/1546139/137680460-27251552-4934-4f07-8079-b56ab7f13335.mp4

**Comment by maverickcdn** [comment]
Probably I pushed a fix not long after,  I forgot to update the file that keeps the update settings.  If you 'cat /jffs/addons/wicens/wicens_update_conf.wic' is there 2 saved variables or 5?  Should be able to force an update and get the hot fix if it didn't find it, you can see the change here https://github.com/maverickcdn/wicens/commit/38af960da9fd09ec548203b8b662c5536240121c#diff-747e863b0a8d7bd165a601afb79c2b6bc4b5d10157180495dcc0851b8bb344cb

Also what ssh client do you use? The colors are wrong im wondering if it's using different terminal defaults.

**Comment by maghuro** [comment]
![Screenshot_2021-10-18-14-45-35-181_com server auditor ssh client](https://user-images.githubusercontent.com/1546139/137743753-e2370c62-d4e5-4cbc-87ce-e743d907e0ee.jpg)
![Screenshot_2021-10-18-14-45-20-568_com server auditor ssh client](https://user-images.githubusercontent.com/1546139/137743755-244da409-c5db-4f7f-945e-c50fb14b5905.jpg)

**Comment by maghuro** [comment]
I use Termius on Android. It has palletes to choose

![Screenshot_2021-10-18-14-46-55-304_com server auditor ssh client](https://user-images.githubusercontent.com/1546139/137743980-bc36d7f0-9422-459f-847e-12d91579df14.jpg)
![Screenshot_2021-10-18-14-46-52-653_com server auditor ssh client](https://user-images.githubusercontent.com/1546139/137743988-1c25208f-65c7-46f1-b6d0-30966e0d354e.jpg)

**Comment by maghuro** [comment]
> Probably I pushed a fix not long after, I forgot to update the file that keeps the update settings. If you 'cat /jffs/addons/wicens/wicens_update_conf.wic' is there 2 saved variables or 5? Should be able to force an update and get the hot fix if it didn't find it, you can see the change here [38af960#diff-747e863b0a8d7bd165a601afb79c2b6bc4b5d10157180495dcc0851b8bb344cb](https://github.com/maverickcdn/wicens/commit/38af960da9fd09ec548203b8b662c5536240121c#diff-747e863b0a8d7bd165a601afb79c2b6bc4b5d10157180495dcc0851b8bb344cb)
> 
> Also what ssh client do you use? The colors are wrong im wondering if it's using different terminal defaults.

I manually removed the update conf file, and the script auto downloaded the new one. Problem solved :)

**Comment by maverickcdn** [comment]
Strange why the update wasnt found... glad to hear though ( I too had an issue after pushing that commit, but its worked every other time).  The update_conf only has 1 user generated variable so I set the script to re-write it on updates and if it was missing.

Under termius-->settings what is your Terminal Type set to?  Should be xterm-256color
![Termius](https://user-images.githubusercontent.com/73246791/137757627-04171db9-ef87-495c-a62a-ab7b84bafc5c.jpg)

**Comment by maverickcdn** [comment]
Could also be color scheme under Host settings... mine is set to Pro

**Comment by maghuro** [comment]
It is xterm-256color...

It was the color scheme. I set to Pro and it turned to be the same as yours :)

**Comment by maghuro** [comment]
Are u sure email notification on update available is flawlessly working?

I manually edited script and changed version number a couple of hours ago.

I haven't received yet any email with an available update notification

**Comment by maverickcdn** [comment]
Come on, you know my coding skills ;)  nothing ever works right the first time haha

Email update checks are only every 4 hours with cron runs, and only sends Email once until you update, you must update to reset the notifcation variables.  You should have a log message if it attempted sending an update notification Email already.

Check /jffs/addons/wicens/wicens_update_conf.wic and make sure 
update_notification= is set to 0   1 means its already sent a message and wont send again till you manually update and that gets reset
update_cron_epoch= needs to be 14400 (4hrs) lower than whatever current epoch time is.

https://github.com/maverickcdn/wicens/blob/3a146690e00386c577c190bf68c3f1f51f0aa73e/wicens.sh#L2398
https://github.com/maverickcdn/wicens/blob/3a146690e00386c577c190bf68c3f1f51f0aa73e/wicens.sh#L2415-L2425

If those two are properly set, you can force a cron run by running with 'wicens.sh cron', then you can recheck the conf file and see those two variables have been updated and you should get a Email notification of either hotfix or script version update, assuming you edited the main script to reflect as such... add a comment line to test md5, OR change the version to test version, version updates ignore md5 changes.

Let me know, Im going to commit some other changes later on after I hear back.

**Comment by maghuro** [comment]
Your coding skills are undoubted :) very good indeed!

Regarding the update config file, the problem is whenever I update the script to a new version, if you add new vars on the new version to this conf file and the file already exists, they aren't created. I have to manually remove the update config file, then update the script (so it creates a new config update file with the new vars).
The script should check whether the config file already exists - if not, create a new one. If yes add the new vars if they don't exist

**Comment by maverickcdn** [comment]
Thanks!

v2.10 has that, and will update the file, but an update was required to be found and installed using menu option u
https://github.com/maverickcdn/wicens/blob/d25f3ccf1977f9c45b5dc87ec35f04bad7619ab3/wicens.sh#L1889
https://github.com/maverickcdn/wicens/blob/d25f3ccf1977f9c45b5dc87ec35f04bad7619ab3/wicens.sh#L1906-L1911
v2.20 
https://github.com/maverickcdn/wicens/blob/d25f3ccf1977f9c45b5dc87ec35f04bad7619ab3/wicens.sh#L2402-L2404
It will rewrite if the file is missing for whatever reason on any call of the script

Also I made the Email update cron period editable in the wicens_update_conf.wic file as update_period=  if you wish to change it from 4 hours.

All my own testing it works well, let me know if you have issues

**Comment by maverickcdn** [comment]
I just realized the issue on the rewrite, even though the new script is downloaded and installed it will still write the old version of F_default_update as the new version isnt loaded into the shell yet.... Ill work on a fix

**Comment by maverickcdn** [comment]
v2.21 fixes this issue, its kinda hacky in my opinion but does what its supposed to, I still have to think out the changelog a little more apparently. v2.22 is current, Ill work on fixing the changelog properly before pushing any more commits.

Notifications are working good for me though, let me know how your testing goes
