### ISSUE TITLE
Not saving password

### ISSUE THREAD

**Issue by bobbydc** [maverickcdn/wicens#2]
I set this up on 2 different routers (different locations). The first one works perfectly, the second not so much. I walk through the setup (exactly the same settings as the first router) and it won't save the password. The main menu shows:

[FAIL] Email send type set to smtp_start_tls but missing required password[-##-] 
Create/edit settings---------: 1     No settings exist

but I've set the password several times over. When I choose option 1, it shows all the settings EXCEPT the password. I reenter it and around we go, won't save.

Any ideas? Appreciate any guidance you could offer.

Running Merlin 384.19_0 on RT-AX58U

**Comment by maverickcdn** [comment]
Sorry for the late reply, I havent been by here in a while.  

Did this work on 1x AX58U but not a second or were they different models?
