### ISSUE TITLE
[Suggestion] Save last IPs

### ISSUE THREAD

**Issue by maghuro** [maverickcdn/wicens#4]
As the title sugests - save the last, let's say, 10 IPs assigned (and send all of them by e-mail everytime the IP changes).

Something like:
"NOTICE

WAN IP for XXXXX has changed 
Sat May 9 2022 15:15:15

New WAN IP is   : XX.XX.XX.XX
________
Old IPs History:
- YY.YY.YY.YY (Sat May 7 2022 10:10:10) // Lease time: 5 day 10 hr 30 min 10 sec
- ZZ.ZZ.ZZ.ZZ (Mon May 2 2022 17:17:17 // Lease time: 1 yr 2 mt 23 day 1 hr 20 min 1 sec
- etc......
"

**Comment by maverickcdn** [comment]
v2.80

Let me know how it works out
