### ISSUE TITLE
Not working on GT-BE98 Pro

### ISSUE THREAD

**Issue by p1r473** [maverickcdn/wicens#7]
I am on latest firmware 3006.102.1-beta 1
```
################################################################################
--------------------------------------------------------------------------------
[FAIL] Sorry this version of firmware is not compatible, please update to 384.15 or newer, or 374 LTS release 48 or newer to utilize this script

sed: /jffs/addons/wicens/wicens_update_conf.wic: No such file or directory
[ OK ] Removed /tmp/wicens_lock.tty lock file
[EXIT] Goodbye :)

```

**Comment by maverickcdn** [comment]
Pushed 4.02 which should hopefully resolve this, let me know...

I don't have a wifi7 device to test any of the functionality of this script, not sure if things like getrealip.sh exist in this FW version or if the nvram variables are the same either.  Please post any errors you come across and I will try to address them.

**Comment by p1r473** [comment]
Doesnt seem to have fixed it when installing via amtm yet, I guess they havent updated on their end yet

**Comment by p1r473** [comment]
Perfect, thanks! all good
